#!/usr/bin/env python3
"""CLI for the hydrogen storage vessel simulation.

  python engine/run.py                        # spec defaults -> out/
  python engine/run.py --q-st 5 --cycles 10
  python engine/run.py --regular-factor 0.85  # sensitivity on the unanchored estimate
  python engine/run.py --capacity-fade 0.02   # 2% loss per cycle
  python engine/run.py --emit-web-constants   # refresh the browser app
"""
from __future__ import annotations

import argparse
import json
import sys
from dataclasses import asdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import model as M
import cycle as C
import deliverables as D

ROOT = Path(__file__).resolve().parent.parent


def emit_web_constants(path: Path, opts: M.Options) -> Path:
    payload = {
        "generated_by": "engine/run.py --emit-web-constants",
        "constants": {"R": M.R, "M_H2": M.M_H2, "T_BENCH": M.T_BENCH,
                      "DOE_TARGET_WT": M.DOE_TARGET_WT,
                      "SAMPLE_MASS_G": M.SAMPLE_MASS_G,
                      "MAX_DESIGN_BAR": M.MAX_DESIGN_BAR},
        "fit": M.FIT,
        "samples": [{"id": s.id, "activation": s.activation, "form": s.form,
                     "label": s.label, "equivalent": s.equivalent} for s in M.SAMPLES],
        "factors": {"powder": M.POWDER_ENHANCEMENT, "binder": M.BINDER_FRACTION,
                    "regular": M.REGULAR_FACTOR},
        "bulk_density": M.BULK_DENSITY,
        "vessel": M.vessel_geometry(),
        "benchmark": {"source": "Langmi et al. (2003) J. Alloys Compd. 356-357, 710-715",
                      "material": "zeolite 5A at 77 K", "data": M.LANGMI_5A_77K},
        "notes": {"regular_factor": M.REGULAR_FACTOR_NOTE},
        "stages": [{"name": n, "minutes": m} for n, m in C.STAGES],
        "dt_min": C.DT_MIN,
        "defaults": asdict(opts),
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    body = json.dumps(payload, indent=2)
    path.write_text(body)
    path.with_suffix(".js").write_text(
        "// Generated by engine/run.py --emit-web-constants. Do not edit by hand.\n"
        "window.MODEL_CONSTANTS = " + body + ";\n")
    return path


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--q-st", type=float, default=6.0, help="kJ/mol; spec says ~5-8")
    ap.add_argument("--t-charge", type=float, default=-78.0, help="°C")
    ap.add_argument("--t-desorb", type=float, default=90.0, help="°C; spec says 80-100")
    ap.add_argument("--p-charge", type=float, default=10.0, help="bar")
    ap.add_argument("--p-discharge", type=float, default=1.0, help="bar")
    ap.add_argument("--cycles", type=int, default=5)
    ap.add_argument("--regular-factor", type=float, default=M.REGULAR_FACTOR)
    ap.add_argument("--capacity-fade", type=float, default=0.0, help="fraction lost per cycle")
    ap.add_argument("--out", type=Path, default=ROOT / "out")
    ap.add_argument("--emit-web-constants", action="store_true")
    a = ap.parse_args(argv)

    opts = M.Options(q_st=a.q_st, T_charge=a.t_charge + 273.15,
                     T_desorb=a.t_desorb + 273.15, P_charge=a.p_charge,
                     P_discharge=a.p_discharge, cycles=a.cycles,
                     regular_factor=a.regular_factor, capacity_fade=a.capacity_fade)

    if a.emit_web_constants:
        p = emit_web_constants(ROOT / "web" / "model-constants.json", opts)
        print(f"web constants -> {p.relative_to(ROOT)}")
        return 0

    res = D.export_all(opts, a.out)
    s = res["summary"]

    print(f"\nVessel Simulation — charge {opts.T_charge-273.15:.0f} °C at {opts.P_charge:g} bar, "
          f"desorb {opts.T_desorb-273.15:.0f} °C, q_st = {opts.q_st:g} kJ/mol, "
          f"{opts.cycles} cycles\n")
    print(f"{'#':<3}{'Sample':<24}{'Charged wt%':>13}{'Working g':>11}{'Peak bar':>10}"
          f"{'% DOE':>9}{'Ads. frac':>11}")
    print("-" * 81)
    for r in s["rows"]:
        flag = " !" if r["exceeds_design_pressure"] else ""
        print(f"{r['id']:<3}{r['label']:<24}{r['charged_wt_pct']:>13.5f}"
              f"{r['working_capacity_g']:>11.5f}{r['peak_pressure_bar']:>9.2f}{flag:<1}"
              f"{r['pct_of_doe_target']:>8.3f}%{r['adsorbed_fraction']*100:>10.1f}%")

    best = next(r for r in s["rows"] if r["id"] == s["best"])
    print(f"\nBest: sample {best['id']} — {best['label']} "
          f"({best['working_capacity_g']:.5f} g working capacity)")
    print(f"DOE gap: best sample reaches {best['pct_of_doe_target']:.2f}% of the "
          f"{M.DOE_TARGET_WT:g} wt% target")
    if s["any_over_pressure"]:
        print(f"WARNING: peak pressure exceeds the {M.MAX_DESIGN_BAR:g} bar design rating "
              f"during sealed heating — see methodology note.")
    if s["identical_cycles"]:
        print("Note: no degradation mechanism specified, so all cycles are identical "
              "by construction.")

    print("\nDeliverables:")
    for k in ("xlsx", "docx", "methodology", "isotherms", "desorption", "cycles",
              "doe", "raw"):
        print(f"  {k:<12} {Path(res[k]).relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
